# Generated by Django 4.0.4 on 2022-05-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('Dbirthday', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('Pbirthday', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=50)),
                ('poids', models.CharField(max_length=50)),
                ('Ssante', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=50)),
                ('cancerType', models.CharField(max_length=50)),
                ('DateDiag', models.CharField(max_length=50)),
                ('medcinNote', models.CharField(max_length=9000)),
                ('MdeFam', models.CharField(max_length=50)),
                ('NumMdeFam', models.CharField(max_length=50)),
                ('Sfin', models.CharField(max_length=50)),
                ('etatCivil', models.CharField(max_length=50)),
            ],
        ),
    ]
